# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Working with Parse as Mobile Backends' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Working with Parse as Mobile Backends
   pod 'Parse'
end
